name: ceqa-env-setup-tools
type: app
base: core24
grade: devel
summary: A tool to setup the test environment on DUT side and server side
description: |
  This program helps QA engineers setup the test environment on the DUT
  and setup a iperf3 server and OBEX server on another device.
version: "0.1"
confinement: devmode

plugs: {}
slots: {}

apps:
  test-env-setup:
    command: test_env_setup_util/env_setup.py
    plugs:
      - home
      - network-bind
      - ssh-keys
      - ssh-public-keys

parts:
  poetry-deps:
    plugin: nil
    build-packages:
      - pipx
    override-build: |
      apt remove python3-poetry -y
      pipx install poetry
      pipx inject poetry poetry-plugin-export
      ln -s /root/.local/bin/poetry /usr/bin/poetry

  poetry-env:
    plugin: poetry
    source: .
    after:
      - poetry-deps

  test-env-setup:
    plugin: dump
    source: test_env_setup_util
    organize:
      "*": test_env_setup_util/
