name: ceqa-env-setup-tools
type: app
base: core24
grade: devel
summary: A tool to setup the test environment on DUT side and server side
description: |
  This program helps QA engineers setup the test environment on the DUT
  and setup a iperf3 server and OBEX server on another device.
version: "0.1"
confinement: classic

plugs: {}
slots: {}

apps:
  test-env-setup:
    # The final command must have this structure for classic confinement
    # 1. Must run `bin/python3 <python file>` and NOT directly invoking the script.
    #   Otherwise system python is used and won't have the libs
    # 2. Anything after the first token must have the $SNAP var in their path
    # If there are more "apps" later, make sure their command follows this example
    command: bin/python3 $SNAP/test_env_setup_util/env_setup.py
    plugs:
      - home
      - network-bind
      - ssh-keys
      - ssh-public-keys

parts:
  dump-files:
    # this just dumps all the files to test_env_setup_util
    # NOTE: ideally we restructure the repo with a src folder so avoid fiddling with pyproject.toml
    plugin: dump
    source: test_env_setup_util
    organize:
      "*": test_env_setup_util/

  run-poetry-plugin:
    # finally run the plugin, see:
    # https://documentation.ubuntu.com/snapcraft/stable/reference/plugins/python_plugin/
    # https://documentation.ubuntu.com/snapcraft/stable/reference/plugins/poetry_plugin/
    plugin: poetry
    source: .
    build-packages:
      - pipx # poetry is distributed with pipx
    # "pipx inject" is needed for the poetry plugin,
    # since the poetry plugin basically asks poetry to export all dependencies,
    # then calls the python plugin to package it
    # also symlink the new poetry we installed with pipx to /root/.local/bin
    override-build: |
      apt remove python3-poetry -y
      pipx install poetry
      pipx inject poetry poetry-plugin-export
      ln -sf /root/.local/bin/poetry /usr/bin/poetry
      snapcraftctl build
    stage-packages:
      # These 3 packages are required for classic confinement
      # do NOT use "python3.12", it's not sufficient
      - python3.12-minimal
      - libpython3.12-minimal
      - libpython3.12-stdlib
    after:
      - dump-files
