name: Test with python-validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.10"
            tox: "py310"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y -qq libgl1 gcc python$PYTHON_VERSION-dev
          pip install tox
          sudo apt-get install black

      - name: Run tox
        run: tox -e${{ matrix.tox }}

      - name: Run black
        run: black --check --diff --line-length 79 ./test_env_setup_util/
