name: Test with markdownlint-cli2

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.10"
            tox: "py310"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: '**/*.md'
